export const DEFAULT = 'default'
export const LOGIN = 'login'
export const POINTS = 'points'
export const REFERENCE_SHOP_BOOKS = 'reference-shop-books'
export const EMPLOYEES = 'employees'
export const EMPLOYEES2 = 'employees2'
export const EDITOR_CREATE_EMPLOYEE = 'edit-or-create-employee'
export const SERVICE_CARDS = 'service-cards'